### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by daaww** [bnkamalesh/goapp#1]
Hi Kamaleshwar,

First of all big thanks the great work you have put here. For someone just starting with go and with the amount of suggestions there I liked the level of details here and the explanation and I find That all make sense to me. That will be awesome to see how you do integration tests also and what do you think about the necessity (or not) of unit-testing (vs interface pollution).

**Comment by bnkamalesh** [comment]
fixed

https://github.com/bnkamalesh/goapp/releases/tag/v1.4.9

https://github.com/bnkamalesh/goapp#internalusers_test
