### ISSUE TITLE
Handle multiple real world domain objects

### ISSUE THREAD

**Issue by coderaing** [bnkamalesh/goapp#2]
First of all thanks @bnkamalesh for the excellent repo. We looked at many golang web boilerplates and this was the best we found!
Since in real world we will have many domains, wont the number of args to [api.NewService](https://github.com/bnkamalesh/goapp/blob/ee45d85a0fa2491a44a5a5b6bc5a7c945b4f3143/internal/api/api.go#L34) become very large? What is a clean way to manage this?

For eg: 
```
type API struct {
	logger        logger.Logger
	users         *users.Users
	notes         *notes.Notes
	blogs         *blogs.Blogs
	subscriptions *subs.Subscriptions
	// ...
}
```

and the corresponding `NewService` like this:
```
// NewService returns a new instance of API with all the dependencies initialized
func NewService(l logger.Logger, us *users.Users, ns *notes.Notes, bs *blogs.Blogs, ss *subs.Subscriptions) (*API, error) {
	return &API{
		logger: l,
		users:  us,
	}, nil
}
```

**Comment by bnkamalesh** [comment]
hey @coderaing you're welcome, and thank you for the feedback. Regarding your query, the Go way of doing it is to make the dependencies fields of a struct and then pass the struct as function argument. But in this case, it would just be redundant. I assume you could make the API struct's fields exported and directly assign from the main function. And you could have a setup/init function on API to validate all the dependencies are setup. Do let me know what are your thoughts on this.

**Comment by coderaing** [comment]
Thanks @bnkamalesh for the response. I think we will go with making the API struct's field public and see how it goes.

**Comment by bnkamalesh** [comment]
Awesome, looking forward to your feedback. Or even better, a PR if you found improvements! 🎉
