### ISSUE TITLE
sqlc

### ISSUE THREAD

**Issue by mahmoudalsof** [bnkamalesh/goapp#6]
Hey! Awesome structure. Probably one of the few I actually like. 
You mention `sqlc` in your docs but don't use it in this repo. I'm curious to see how you handle the generated code. I typically prefer to split queries based on table and then output the generated code to its separate package. Where would you put these packages?

**Comment by bnkamalesh** [comment]
hey @mahmoudalsof thank you for the feedback, hope you find it useful for your projects!

Regarding `sqlc`, Squirrel (query builders) in general are in my opinion _easier_ most of the time, hence I used Squirrel in this repository. Though in case of generated packages (like sqlc), I would prefer they remain as close as possible to the store functions. An example with respect to this application would be, to place the generated packages within
`internal/usernotes/gen/<packages>`. This way it'd not clutter your code, and is contained within the respective **_domain_**.
